spring:
  application:
    name: msvc-auth_and_profile
  config:
    import: optional:configserver:http://172.31.11.92:8888

jwt:
  secret: MiAVzqUXy5Tfr1kVIGpPMiAVzqUXy5Tfr1kVIGpP
  expiration: 86400