server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: employees
          uri: 'http://3.142.156.144:8090'
          predicates:
            - Path=/api/redcorp/v1/employee/**
        - id: sections
          uri: 'http://3.142.156.144:9090'
          predicates:
            - Path=/api/redcorp/v1/section/**
        - id: auth
          uri: 'http://3.142.156.144:8090'
          predicates:
            - Path=/api/redcorp/v1/auth/**
        - id: sections
          uri: 'http://3.142.156.144:9090'
          predicates:
            - Path=/api/redcorp/v1/team/**
        - id: sections
          uri: 'http://3.142.156.144:9090'
          predicates:
            - Path=/api/redcorp/v1/project/**
        - id: sections
          uri: 'http://3.142.156.144:8070'
          predicates:
            - Path=/api/redcorp/v1/task/**

eureka:
  client:
    register-with-eureka: false