server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: employees
          uri: 'http://localhost:8090'
          predicates:
            - Path=/api/redcorp/v1/employee/**
        - id: sections
          uri: 'http://localhost:9090'
          predicates:
            - Path=/api/redcorp/v1/section/**
        - id: auth
          uri: 'http://localhost:8090'
          predicates:
            - Path=/api/redcorp/v1/auth/**

eureka:
  client:
    register-with-eureka: false