server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: employees
          uri: 'http://172.31.11.92:8090'
          predicates:
            - Path=/api/redcorp/v1/employee/**
        - id: sections
          uri: 'http://172.31.11.92:9090'
          predicates:
            - Path=/api/redcorp/v1/section/**
        - id: auth
          uri: 'http://172.31.11.92:8090'
          predicates:
            - Path=/api/redcorp/v1/auth/**
        - id: sections
          uri: 'http://172.31.11.92:9090'
          predicates:
            - Path=/api/redcorp/v1/team/**
        - id: sections
          uri: 'http://172.31.11.92:9090'
          predicates:
            - Path=/api/redcorp/v1/project/**
        - id: sections
          uri: 'http://172.31.11.92:8070'
          predicates:
            - Path=/api/redcorp/v1/task/**

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://172.31.11.92:8761/eureka/